name: Deploy

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read package.json and get version
        id: get-version
        run: echo "::set-output name=version::$(node -e 'console.log(require("./package.json").version)')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push integration service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Update this path if your Dockerfile is in a different location
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webpage:${{ steps.get-version.outputs.version }}